### ISSUE TITLE
undefined method 'client_ip' for HTTP::Server::Context

### ISSUE THREAD

**Issue by jwoertink** [fridgerator/bugsnag#1]
This happens on crystal 0.25.1 and 0.26.1

```
in lib/bugsnag/src/bugsnag.cr:16: instantiating 'Bugsnag::Event:Class#new(HTTP::Server::Context, Exception+)'

      event = Event.new(context, exception)
                    ^~~

in lib/bugsnag/src/bugsnag/event.cr:27: instantiating 'Bugsnag::Request:Class#new(HTTP::Server::Context)'

      @request = Request.new(context)
                         ^~~

in lib/bugsnag/src/bugsnag/request.cr:14: undefined method 'client_ip' for HTTP::Server::Context

      @client_ip = context.client_ip.to_s
                           ^~~~~~~~~
```

**Comment by jwoertink** [comment]
It looks like this might be from [Amber](https://github.com/amberframework/amber/blob/master/src/amber/extensions/http.cr#L4)? I'm using Lucky, so this method doesn't seem to exist.

**Comment by fridgerator** [comment]
Yeah this is for Amber (or my "fork" of it, rather).  I was going to make this more generic and check if `client_ip` was defined, if not use the `X-Forwarded-For` header if it exists, but I forgot.

**Comment by jwoertink** [comment]
I hope that it gets added in to core crystal soon. Looks like issues are still open about that.

**Comment by fridgerator** [comment]
Yeah me too!  Meanwhile, does the commit I just pushed to master solve the issue?

**Comment by jwoertink** [comment]
yup! Boots and sends reports. Thanks!
