### ISSUE TITLE
Changing the release_stage

### ISSUE THREAD

**Issue by jwoertink** [fridgerator/bugsnag#2]
I'm not seeing a way to configure this. Without just hand-rolling the whole process with my own custom `Bugsnag.report` method. It looks like it just always defaults to "production". Maybe it could be moved the the Config class and just default from there? That way doing `Bugsnag.config.env = ENV["whatever_i_want"]`?

**Comment by fridgerator** [comment]
@jwoertink I added a commit to master, which adds `release_stage` to the `Bugsnag.config`.  You can also set this using `ENV["BUGSNAG_RELEASE_STAGE"]`.  Does this help?

**Comment by jwoertink** [comment]
yup! I think that will work great. Thanks!
